import type { Tool } from '@/types'

// ─── Complete Tool Registry ────────────────────────────────────────────────────

export const TOOLS: Tool[] = [
  // ── PDF Essentials ──────────────────────────────────────────────────────────
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document.',
    longDescription: 'Easily merge multiple PDF files into one seamless document. Drag and drop to reorder, then download your combined PDF instantly — all processed locally.',
    category: 'pdf',
    icon: 'link',
    color: '#8B5CF6',
    route: '/tools/pdf/merge-pdf',
    tags: ['merge', 'combine', 'join', 'pdf'],
    isFeatured: true,
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    supportsMultipleFiles: true,
    relatedTools: ['split-pdf', 'compress-pdf', 'organize-pdf']
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Split a PDF into multiple documents by page ranges.',
    longDescription: 'Extract specific pages or split a PDF into individual pages. Define custom ranges like "1-3, 5, 7-9" or split every page into a separate file.',
    category: 'pdf',
    icon: 'call_split',
    color: '#6366f1',
    route: '/tools/pdf/split-pdf',
    tags: ['split', 'separate', 'extract', 'pages', 'pdf'],
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['merge-pdf', 'extract-pages', 'delete-pages']
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality.',
    longDescription: 'Shrink your PDF files for easy sharing via email or upload. Choose from multiple compression levels to balance quality and file size.',
    category: 'pdf',
    icon: 'compress',
    color: '#EF4444',
    route: '/tools/pdf/compress-pdf',
    tags: ['compress', 'reduce', 'shrink', 'optimize', 'pdf'],
    isFeatured: true,
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['merge-pdf', 'repair-pdf']
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files.',
    category: 'pdf',
    icon: 'build',
    color: '#6366f1',
    route: '/tools/pdf/repair-pdf',
    tags: ['repair', 'fix', 'corrupt', 'damaged', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['compress-pdf', 'flatten-pdf']
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDFs',
    description: 'Compare two PDF documents and highlight differences.',
    category: 'pdf',
    icon: 'compare',
    color: '#6366f1',
    route: '/tools/pdf/compare-pdf',
    tags: ['compare', 'diff', 'difference', 'pdf'],
    isNew: true,
    acceptedFileTypes: ['.pdf'],
    supportsMultipleFiles: true,
    relatedTools: ['merge-pdf', 'overlay-pdf']
  },
  {
    id: 'create-pdf',
    name: 'Create PDF',
    description: 'Create a new PDF from images, text, or blank pages.',
    category: 'pdf',
    icon: 'post_add',
    color: '#6366f1',
    route: '/tools/pdf/create-pdf',
    tags: ['create', 'new', 'blank', 'make', 'pdf'],
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp', '.txt'],
    outputFileTypes: ['.pdf'],
    supportsMultipleFiles: true,
    relatedTools: ['image-to-pdf', 'txt-to-pdf']
  },
  {
    id: 'optimize-pdf',
    name: 'Optimize PDF',
    description: 'Optimize PDF for web, print, or archiving.',
    category: 'pdf',
    icon: 'tune',
    color: '#6366f1',
    route: '/tools/pdf/optimize-pdf',
    tags: ['optimize', 'web', 'print', 'archive', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Flatten PDF forms and annotations into static content.',
    category: 'pdf',
    icon: 'layers_clear',
    color: '#6366f1',
    route: '/tools/pdf/flatten-pdf',
    tags: ['flatten', 'forms', 'annotations', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },

  // ── PDF Organization ────────────────────────────────────────────────────────
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Drag, reorder, rotate, and delete pages visually.',
    category: 'pdf',
    icon: 'grid_view',
    color: '#6366f1',
    route: '/tools/pdf/organize-pdf',
    tags: ['organize', 'reorder', 'rotate', 'delete', 'pages', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['reorder-pages', 'rotate-pages', 'delete-pages']
  },
  {
    id: 'reorder-pages',
    name: 'Reorder Pages',
    description: 'Drag and drop to rearrange pages in your PDF.',
    category: 'pdf',
    icon: 'swap_vert',
    color: '#6366f1',
    route: '/tools/pdf/reorder-pages',
    tags: ['reorder', 'rearrange', 'pages', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'rotate-pages',
    name: 'Rotate Pages',
    description: 'Rotate one or all pages in your PDF 90° or 180°.',
    category: 'pdf',
    icon: 'rotate_right',
    color: '#6366f1',
    route: '/tools/pdf/rotate-pages',
    tags: ['rotate', 'orientation', 'pages', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    description: 'Remove unwanted pages from your PDF.',
    category: 'pdf',
    icon: 'delete_sweep',
    color: '#6366f1',
    route: '/tools/pdf/delete-pages',
    tags: ['delete', 'remove', 'pages', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Extract selected pages from a PDF into a new file.',
    category: 'pdf',
    icon: 'file_copy',
    color: '#6366f1',
    route: '/tools/pdf/extract-pages',
    tags: ['extract', 'pages', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'duplicate-pages',
    name: 'Duplicate Pages',
    description: 'Duplicate specific pages within a PDF.',
    category: 'pdf',
    icon: 'content_copy',
    color: '#6366f1',
    route: '/tools/pdf/duplicate-pages',
    tags: ['duplicate', 'copy', 'pages', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'reverse-pdf',
    name: 'Reverse PDF',
    description: 'Reverse the page order of a PDF document.',
    category: 'pdf',
    icon: 'swap_calls',
    color: '#6366f1',
    route: '/tools/pdf/reverse-pdf',
    tags: ['reverse', 'order', 'pages', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'alternate-mix',
    name: 'Alternate & Mix PDFs',
    description: 'Interleave pages from two PDFs alternately.',
    category: 'pdf',
    icon: 'shuffle',
    color: '#6366f1',
    route: '/tools/pdf/alternate-mix',
    tags: ['alternate', 'mix', 'interleave', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    supportsMultipleFiles: true,
    outputFileTypes: ['.pdf']
  },
  {
    id: 'insert-blank-pages',
    name: 'Insert Blank Pages',
    description: 'Insert blank pages at any position in your PDF.',
    category: 'pdf',
    icon: 'note_add',
    color: '#6366f1',
    route: '/tools/pdf/insert-blank-pages',
    tags: ['insert', 'blank', 'pages', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'replace-pages',
    name: 'Replace Pages',
    description: 'Replace specific pages with pages from another PDF.',
    category: 'pdf',
    icon: 'find_replace',
    color: '#6366f1',
    route: '/tools/pdf/replace-pages',
    tags: ['replace', 'pages', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },

  // ── PDF Editing ─────────────────────────────────────────────────────────────
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add text or image watermarks to your PDF.',
    category: 'edit',
    icon: 'branding_watermark',
    color: '#f59e0b',
    route: '/tools/edit/watermark-pdf',
    tags: ['watermark', 'stamp', 'text', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['add-page-numbers', 'header-footer']
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to any position on your PDF.',
    category: 'edit',
    icon: 'format_list_numbered',
    color: '#f59e0b',
    route: '/tools/edit/add-page-numbers',
    tags: ['page numbers', 'numbering', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'header-footer',
    name: 'Header & Footer',
    description: 'Add custom headers and footers to your PDF.',
    category: 'edit',
    icon: 'vertical_align_top',
    color: '#f59e0b',
    route: '/tools/edit/header-footer',
    tags: ['header', 'footer', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'background-pdf',
    name: 'Background PDF',
    description: 'Add a background color or image to your PDF.',
    category: 'edit',
    icon: 'wallpaper',
    color: '#f59e0b',
    route: '/tools/edit/background-pdf',
    tags: ['background', 'color', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'overlay-pdf',
    name: 'Overlay PDF',
    description: 'Overlay one PDF on top of another.',
    category: 'edit',
    icon: 'layers',
    color: '#f59e0b',
    route: '/tools/edit/overlay-pdf',
    tags: ['overlay', 'stamp', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'metadata-editor',
    name: 'Metadata Editor',
    description: 'Edit PDF metadata: title, author, subject, keywords.',
    category: 'edit',
    icon: 'info',
    color: '#f59e0b',
    route: '/tools/edit/metadata-editor',
    tags: ['metadata', 'properties', 'title', 'author', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'add-text',
    name: 'Add Text',
    description: 'Add and edit text anywhere in your PDF.',
    category: 'edit',
    icon: 'text_fields',
    color: '#f59e0b',
    route: '/tools/edit/add-text',
    tags: ['text', 'add', 'edit', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'add-images-to-pdf',
    name: 'Add Images',
    description: 'Insert images into your PDF documents.',
    category: 'edit',
    icon: 'add_photo_alternate',
    color: '#f59e0b',
    route: '/tools/edit/add-images',
    tags: ['image', 'insert', 'add', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'highlight-pdf',
    name: 'Highlight PDF',
    description: 'Highlight text and add markup to PDF documents.',
    category: 'edit',
    icon: 'highlight',
    color: '#f59e0b',
    route: '/tools/edit/highlight-pdf',
    tags: ['highlight', 'markup', 'annotate', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'annotate-pdf',
    name: 'Annotate PDF',
    description: 'Add comments, notes, and annotations to PDFs.',
    category: 'edit',
    icon: 'comment',
    color: '#f59e0b',
    route: '/tools/edit/annotate-pdf',
    tags: ['annotate', 'comment', 'note', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'fill-forms',
    name: 'Fill PDF Forms',
    description: 'Fill out PDF forms without any software.',
    category: 'edit',
    icon: 'assignment',
    color: '#f59e0b',
    route: '/tools/edit/fill-forms',
    tags: ['form', 'fill', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'create-forms',
    name: 'Create PDF Forms',
    description: 'Create interactive PDF forms with fillable fields.',
    category: 'edit',
    icon: 'dynamic_form',
    color: '#f59e0b',
    route: '/tools/edit/create-forms',
    tags: ['form', 'create', 'fields', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },

  // ── Security ────────────────────────────────────────────────────────────────
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Password protect and secure your PDF files.',
    longDescription: 'Add password protection to your PDF to prevent unauthorized access. Set user and owner passwords, and configure permissions for printing, copying, and editing.',
    category: 'security',
    icon: 'lock',
    color: '#8B5CF6',
    route: '/tools/security/protect-pdf',
    tags: ['protect', 'password', 'encrypt', 'security', 'pdf'],
    isFeatured: true,
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['unlock-pdf', 'redact-pdf']
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDF files.',
    category: 'security',
    icon: 'lock_open',
    color: '#ef4444',
    route: '/tools/security/unlock-pdf',
    tags: ['unlock', 'password', 'decrypt', 'security', 'pdf'],
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['protect-pdf']
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive content from PDFs.',
    category: 'security',
    icon: 'hide_source',
    color: '#ef4444',
    route: '/tools/security/redact-pdf',
    tags: ['redact', 'remove', 'sensitive', 'privacy', 'pdf'],
    isNew: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'metadata-cleaner',
    name: 'Metadata Cleaner',
    description: 'Strip all metadata and hidden data from PDFs.',
    category: 'security',
    icon: 'cleaning_services',
    color: '#ef4444',
    route: '/tools/security/metadata-cleaner',
    tags: ['metadata', 'clean', 'strip', 'privacy', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'encryption',
    name: 'PDF Encryption',
    description: 'Advanced AES-256 encryption for PDF documents.',
    category: 'security',
    icon: 'enhanced_encryption',
    color: '#ef4444',
    route: '/tools/security/encryption',
    tags: ['encrypt', 'aes', 'security', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'privacy-scanner',
    name: 'Privacy Scanner',
    description: 'Scan PDF for personal data and privacy risks.',
    category: 'security',
    icon: 'policy',
    color: '#ef4444',
    route: '/tools/security/privacy-scanner',
    tags: ['privacy', 'scan', 'pii', 'gdpr', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'bates-numbering',
    name: 'Bates Numbering',
    description: 'Add Bates numbers to PDF documents for legal use.',
    category: 'security',
    icon: 'tag',
    color: '#ef4444',
    route: '/tools/security/bates-numbering',
    tags: ['bates', 'legal', 'numbering', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'permission-management',
    name: 'Permission Management',
    description: 'Set granular permissions for PDF documents.',
    category: 'security',
    icon: 'manage_accounts',
    color: '#ef4444',
    route: '/tools/security/permission-management',
    tags: ['permissions', 'print', 'copy', 'edit', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },

  // ── OCR & Scan ──────────────────────────────────────────────────────────────
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Extract text from scanned documents and images.',
    longDescription: 'Convert scanned PDFs into searchable, selectable text using Tesseract OCR. Supports 20+ languages. All processing happens locally in your browser.',
    category: 'ocr',
    icon: 'document_scanner',
    color: '#14B8A6',
    route: '/tools/ocr/ocr-pdf',
    tags: ['ocr', 'scan', 'text', 'extract', 'pdf'],
    isFeatured: true,
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.txt', '.pdf'],
    relatedTools: ['ocr-images', 'searchable-pdf']
  },
  {
    id: 'ocr-images',
    name: 'OCR Images',
    description: 'Extract text from images using optical character recognition.',
    category: 'ocr',
    icon: 'image_search',
    color: '#10b981',
    route: '/tools/ocr/ocr-images',
    tags: ['ocr', 'image', 'text', 'extract'],
    isPopular: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff'],
    outputFileTypes: ['.txt'],
    supportsMultipleFiles: true
  },
  {
    id: 'searchable-pdf',
    name: 'Searchable PDF',
    description: 'Make a scanned PDF fully text-searchable.',
    category: 'ocr',
    icon: 'find_in_page',
    color: '#10b981',
    route: '/tools/ocr/searchable-pdf',
    tags: ['searchable', 'ocr', 'text', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'batch-ocr',
    name: 'Batch OCR',
    description: 'Process multiple images or PDFs with OCR at once.',
    category: 'ocr',
    icon: 'batch_prediction',
    color: '#10b981',
    route: '/tools/ocr/batch-ocr',
    tags: ['batch', 'ocr', 'multiple', 'scan'],
    acceptedFileTypes: ['.pdf', '.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.txt'],
    supportsMultipleFiles: true
  },
  {
    id: 'camera-scanner',
    name: 'Camera Scanner',
    description: 'Use your device camera to scan documents.',
    category: 'ocr',
    icon: 'photo_camera',
    color: '#10b981',
    route: '/tools/ocr/camera-scanner',
    tags: ['camera', 'scan', 'document'],
    isNew: true,
    isComingSoon: true
  },
  {
    id: 'deskew',
    name: 'Deskew',
    description: 'Automatically straighten skewed scanned documents.',
    category: 'ocr',
    icon: 'straighten',
    color: '#10b981',
    route: '/tools/ocr/deskew',
    tags: ['deskew', 'straighten', 'scan'],
    isNew: true,
    isComingSoon: true
  },
  {
    id: 'text-extraction',
    name: 'Text Extraction',
    description: 'Extract all text content from a PDF document.',
    category: 'ocr',
    icon: 'text_snippet',
    color: '#10b981',
    route: '/tools/ocr/text-extraction',
    tags: ['extract', 'text', 'content', 'pdf'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.txt']
  },

  // ── Conversion ──────────────────────────────────────────────────────────────
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files to editable Word documents.',
    category: 'convert',
    icon: 'description',
    color: '#22C55E',
    route: '/tools/convert/pdf-to-word',
    tags: ['pdf', 'word', 'docx', 'convert'],
    isFeatured: true,
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.docx'],
    relatedTools: ['word-to-pdf', 'pdf-to-txt']
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from PDF to Excel spreadsheets.',
    category: 'convert',
    icon: 'table_chart',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-excel',
    tags: ['pdf', 'excel', 'xlsx', 'table', 'convert'],
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.xlsx']
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF presentations to editable PowerPoint files.',
    category: 'convert',
    icon: 'slideshow',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-powerpoint',
    tags: ['pdf', 'powerpoint', 'pptx', 'convert'],
    isNew: true,
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pptx']
  },
  {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    description: 'Convert PDF documents to HTML web pages.',
    category: 'convert',
    icon: 'html',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-html',
    tags: ['pdf', 'html', 'web', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.html']
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    description: 'Convert PDF content to Markdown format.',
    category: 'convert',
    icon: 'code',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-markdown',
    tags: ['pdf', 'markdown', 'md', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.md']
  },
  {
    id: 'pdf-to-txt',
    name: 'PDF to TXT',
    description: 'Extract all text from a PDF as a plain text file.',
    category: 'convert',
    icon: 'text_snippet',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-txt',
    tags: ['pdf', 'txt', 'text', 'extract', 'convert'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.txt']
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page to a JPG image.',
    category: 'convert',
    icon: 'photo',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-jpg',
    tags: ['pdf', 'jpg', 'image', 'convert'],
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.jpg']
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Convert each PDF page to a PNG image.',
    category: 'convert',
    icon: 'image',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-png',
    tags: ['pdf', 'png', 'image', 'convert'],
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.png']
  },
  {
    id: 'pdf-to-svg',
    name: 'PDF to SVG',
    description: 'Convert PDF pages to scalable SVG vector graphics.',
    category: 'convert',
    icon: 'polyline',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-svg',
    tags: ['pdf', 'svg', 'vector', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.svg']
  },
  {
    id: 'pdf-to-webp',
    name: 'PDF to WebP',
    description: 'Convert PDF pages to modern WebP format images.',
    category: 'convert',
    icon: 'photo_library',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-webp',
    tags: ['pdf', 'webp', 'image', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.webp']
  },
  {
    id: 'pdf-to-epub',
    name: 'PDF to EPUB',
    description: 'Convert PDF books to EPUB ebook format.',
    category: 'convert',
    icon: 'menu_book',
    color: '#3b82f6',
    route: '/tools/convert/pdf-to-epub',
    tags: ['pdf', 'epub', 'ebook', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.epub']
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word DOCX files to PDF format.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/word-to-pdf',
    tags: ['word', 'docx', 'pdf', 'convert'],
    isPopular: true,
    acceptedFileTypes: ['.docx', '.doc'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['pdf-to-word']
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF documents.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/excel-to-pdf',
    tags: ['excel', 'xlsx', 'pdf', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.xlsx', '.xls'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'pptx-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/pptx-to-pdf',
    tags: ['powerpoint', 'pptx', 'pdf', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.pptx', '.ppt'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML pages or web content to PDF.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/html-to-pdf',
    tags: ['html', 'web', 'pdf', 'convert'],
    acceptedFileTypes: ['.html', '.htm'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    description: 'Convert Markdown files to beautifully formatted PDFs.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/markdown-to-pdf',
    tags: ['markdown', 'md', 'pdf', 'convert'],
    isNew: true,
    acceptedFileTypes: ['.md', '.markdown'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'txt-to-pdf',
    name: 'TXT to PDF',
    description: 'Convert plain text files to PDF documents.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/txt-to-pdf',
    tags: ['txt', 'text', 'pdf', 'convert'],
    acceptedFileTypes: ['.txt'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images (JPG, PNG, WebP) to PDF documents.',
    category: 'convert',
    icon: 'image',
    color: '#22C55E',
    route: '/tools/convert/image-to-pdf',
    tags: ['image', 'jpg', 'png', 'pdf', 'convert'],
    isPopular: true,
    isNew: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp', '.bmp'],
    outputFileTypes: ['.pdf'],
    supportsMultipleFiles: true
  },
  {
    id: 'csv-to-xlsx',
    name: 'CSV to XLSX',
    description: 'Convert CSV files to Excel spreadsheets.',
    category: 'convert',
    icon: 'table_chart',
    color: '#3b82f6',
    route: '/tools/convert/csv-to-xlsx',
    tags: ['csv', 'xlsx', 'excel', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.csv'],
    outputFileTypes: ['.xlsx']
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON data files to CSV format.',
    category: 'convert',
    icon: 'data_object',
    color: '#3b82f6',
    route: '/tools/convert/json-to-csv',
    tags: ['json', 'csv', 'convert', 'data'],
    isComingSoon: true,
    acceptedFileTypes: ['.json'],
    outputFileTypes: ['.csv']
  },
  {
    id: 'epub-to-pdf',
    name: 'EPUB to PDF',
    description: 'Convert EPUB ebooks to PDF format.',
    category: 'convert',
    icon: 'picture_as_pdf',
    color: '#3b82f6',
    route: '/tools/convert/epub-to-pdf',
    tags: ['epub', 'ebook', 'pdf', 'convert'],
    isComingSoon: true,
    acceptedFileTypes: ['.epub'],
    outputFileTypes: ['.pdf']
  },

  // ── Image Tools ─────────────────────────────────────────────────────────────
  {
    id: 'compress-images',
    name: 'Compress Images',
    description: 'Reduce image file size without losing quality.',
    category: 'image',
    icon: 'photo_size_select_small',
    color: '#ec4899',
    route: '/tools/image/compress-images',
    tags: ['compress', 'image', 'reduce', 'size'],
    isPopular: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.jpg', '.png', '.webp'],
    supportsMultipleFiles: true
  },
  {
    id: 'convert-images',
    name: 'Convert Images',
    description: 'Convert images between JPG, PNG, WebP, GIF, and more.',
    category: 'image',
    icon: 'swap_horiz',
    color: '#ec4899',
    route: '/tools/image/convert-images',
    tags: ['convert', 'image', 'format', 'jpg', 'png', 'webp'],
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp'],
    outputFileTypes: ['.jpg', '.png', '.webp'],
    supportsMultipleFiles: true
  },
  {
    id: 'resize-images',
    name: 'Resize Images',
    description: 'Resize images to any dimension while preserving aspect ratio.',
    category: 'image',
    icon: 'photo_size_select_large',
    color: '#ec4899',
    route: '/tools/image/resize-images',
    tags: ['resize', 'image', 'scale', 'dimension'],
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.jpg', '.png', '.webp'],
    supportsMultipleFiles: true
  },
  {
    id: 'crop-images',
    name: 'Crop Images',
    description: 'Crop images to any size or aspect ratio.',
    category: 'image',
    icon: 'crop',
    color: '#ec4899',
    route: '/tools/image/crop-images',
    tags: ['crop', 'image', 'trim'],
    isComingSoon: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.jpg', '.png']
  },
  {
    id: 'rotate-images',
    name: 'Rotate Images',
    description: 'Rotate images 90°, 180°, or any custom angle.',
    category: 'image',
    icon: 'rotate_90_degrees_ccw',
    color: '#ec4899',
    route: '/tools/image/rotate-images',
    tags: ['rotate', 'image', 'flip'],
    isComingSoon: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.jpg', '.png']
  },
  {
    id: 'watermark-images',
    name: 'Watermark Images',
    description: 'Add text or logo watermarks to images.',
    category: 'image',
    icon: 'branding_watermark',
    color: '#ec4899',
    route: '/tools/image/watermark-images',
    tags: ['watermark', 'image', 'stamp'],
    isComingSoon: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.jpg', '.png']
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    description: 'Automatically remove the background from images.',
    category: 'image',
    icon: 'layers_clear',
    color: '#8B5CF6',
    route: '/tools/image/remove-background',
    tags: ['background', 'remove', 'transparent', 'image'],
    isNew: true,
    isComingSoon: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png'],
    outputFileTypes: ['.png']
  },
  {
    id: 'image-enhancement',
    name: 'Image Enhancement',
    description: 'Adjust brightness, contrast, saturation, and sharpness.',
    category: 'image',
    icon: 'tonality',
    color: '#ec4899',
    route: '/tools/image/image-enhancement',
    tags: ['enhance', 'brightness', 'contrast', 'image'],
    isComingSoon: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFileTypes: ['.jpg', '.png']
  },
  {
    id: 'passport-photo',
    name: 'Passport Photo',
    description: 'Generate passport and visa photos to any specification.',
    category: 'image',
    icon: 'portrait',
    color: '#ec4899',
    route: '/tools/image/passport-photo',
    tags: ['passport', 'photo', 'id', 'visa'],
    isComingSoon: true
  },
  {
    id: 'batch-image',
    name: 'Batch Image Processing',
    description: 'Process multiple images simultaneously.',
    category: 'image',
    icon: 'burst_mode',
    color: '#ec4899',
    route: '/tools/image/batch-image',
    tags: ['batch', 'image', 'multiple'],
    isComingSoon: true,
    supportsMultipleFiles: true
  },

  // ── Signature ───────────────────────────────────────────────────────────────
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add electronic signatures to PDF documents.',
    longDescription: 'Add your electronic signature to any PDF document. Draw with your mouse, type your name in a cursive font, or upload an existing signature image.',
    category: 'signature',
    icon: 'draw',
    color: '#F59E0B',
    route: '/tools/signature/sign-pdf',
    tags: ['sign', 'signature', 'esign', 'pdf'],
    isFeatured: true,
    isPopular: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf'],
    relatedTools: ['protect-pdf', 'fill-forms']
  },
  {
    id: 'signature-templates',
    name: 'Signature Templates',
    description: 'Create and save signature templates for reuse.',
    category: 'signature',
    icon: 'style',
    color: '#8b5cf6',
    route: '/tools/signature/signature-templates',
    tags: ['signature', 'template', 'save'],
    isComingSoon: true
  },
  {
    id: 'multi-signature',
    name: 'Multi-Signature',
    description: 'Collect multiple signatures on a single document.',
    category: 'signature',
    icon: 'group',
    color: '#8b5cf6',
    route: '/tools/signature/multi-signature',
    tags: ['multi', 'signature', 'multiple', 'pdf'],
    isComingSoon: true
  },
  {
    id: 'initials-stamp',
    name: 'Initials & Stamp',
    description: 'Add initials and custom stamps to PDF pages.',
    category: 'signature',
    icon: 'approval',
    color: '#F59E0B',
    route: '/tools/signature/initials-stamp',
    tags: ['stamp', 'initials', 'signature', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'signature-request',
    name: 'Signature Request',
    description: 'Prepare documents for signature collection workflows.',
    category: 'signature',
    icon: 'mark_email_read',
    color: '#F59E0B',
    route: '/tools/signature/signature-request',
    tags: ['request', 'signature', 'workflow', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'date-signed',
    name: 'Date Signed',
    description: 'Stamp signed-on dates next to electronic signatures.',
    category: 'signature',
    icon: 'event',
    color: '#F59E0B',
    route: '/tools/signature/date-signed',
    tags: ['date', 'signature', 'stamp', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'signature-certificate',
    name: 'Signature Certificate',
    description: 'Generate a local signature audit certificate for a PDF.',
    category: 'signature',
    icon: 'workspace_premium',
    color: '#F59E0B',
    route: '/tools/signature/signature-certificate',
    tags: ['certificate', 'audit', 'signature', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },

  // ── Document Tools ──────────────────────────────────────────────────────────
  {
    id: 'epub-generator',
    name: 'EPUB Generator',
    description: 'Create EPUB ebooks from text, Markdown, or HTML files.',
    category: 'document',
    icon: 'menu_book',
    color: '#3B82F6',
    route: '/tools/document/epub-generator',
    tags: ['epub', 'ebook', 'document', 'generator'],
    isNew: true,
    acceptedFileTypes: ['.txt', '.md', '.html'],
    outputFileTypes: ['.epub']
  },
  {
    id: 'combine-word',
    name: 'Combine Word',
    description: 'Merge multiple Word documents into one file.',
    category: 'document',
    icon: 'library_books',
    color: '#3B82F6',
    route: '/tools/document/combine-word',
    tags: ['word', 'docx', 'merge', 'document'],
    isComingSoon: true,
    acceptedFileTypes: ['.docx', '.doc'],
    supportsMultipleFiles: true
  },
  {
    id: 'excel-split',
    name: 'Split Excel',
    description: 'Split Excel workbooks into separate sheets or files.',
    category: 'document',
    icon: 'grid_on',
    color: '#22C55E',
    route: '/tools/document/excel-split',
    tags: ['excel', 'xlsx', 'split', 'document'],
    isComingSoon: true,
    acceptedFileTypes: ['.xlsx', '.xls']
  },
  {
    id: 'pptx-extract',
    name: 'Extract PowerPoint',
    description: 'Extract slides, notes, and images from presentations.',
    category: 'document',
    icon: 'slideshow',
    color: '#F59E0B',
    route: '/tools/document/pptx-extract',
    tags: ['powerpoint', 'pptx', 'extract', 'document'],
    isComingSoon: true,
    acceptedFileTypes: ['.pptx', '.ppt']
  },
  {
    id: 'html-document',
    name: 'HTML Document',
    description: 'Preview and export HTML files as clean documents.',
    category: 'document',
    icon: 'html',
    color: '#F97316',
    route: '/tools/document/html-document',
    tags: ['html', 'preview', 'document'],
    isComingSoon: true,
    acceptedFileTypes: ['.html', '.htm']
  },
  {
    id: 'markdown-document',
    name: 'Markdown Document',
    description: 'Edit and export Markdown files for publishing.',
    category: 'document',
    icon: 'edit_note',
    color: '#A1A1AA',
    route: '/tools/document/markdown-document',
    tags: ['markdown', 'md', 'document'],
    isComingSoon: true,
    acceptedFileTypes: ['.md', '.markdown']
  },
  {
    id: 'odt-to-docx',
    name: 'ODT to Word',
    description: 'Convert OpenDocument text files to Word format.',
    category: 'document',
    icon: 'description',
    color: '#3B82F6',
    route: '/tools/document/odt-to-docx',
    tags: ['odt', 'word', 'docx', 'document'],
    isComingSoon: true,
    acceptedFileTypes: ['.odt'],
    outputFileTypes: ['.docx']
  },
  {
    id: 'document-templates',
    name: 'Document Templates',
    description: 'Start from reusable Word, Excel, and letter templates.',
    category: 'document',
    icon: 'article',
    color: '#8B5CF6',
    route: '/tools/document/document-templates',
    tags: ['template', 'word', 'excel', 'document'],
    isComingSoon: true
  },

  // ── Business Tools ──────────────────────────────────────────────────────────
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create professional invoices and download as PDF.',
    category: 'business',
    icon: 'receipt_long',
    color: '#f97316',
    route: '/tools/business/invoice-generator',
    tags: ['invoice', 'billing', 'business', 'pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'gst-invoice',
    name: 'GST Invoice Generator',
    description: 'Create GST-compliant tax invoices for Indian businesses.',
    category: 'business',
    icon: 'request_quote',
    color: '#f97316',
    route: '/tools/business/gst-invoice',
    tags: ['gst', 'invoice', 'tax', 'india', 'pdf'],
    outputFileTypes: ['.pdf']
  },
  {
    id: 'receipt-generator',
    name: 'Receipt Generator',
    description: 'Generate payment receipts for your business.',
    category: 'business',
    icon: 'receipt',
    color: '#f97316',
    route: '/tools/business/receipt-generator',
    tags: ['receipt', 'payment', 'business'],
    isComingSoon: true,
    outputFileTypes: ['.pdf']
  },
  {
    id: 'thermal-receipt',
    name: 'Thermal Receipt',
    description: 'Generate 80mm thermal printer receipt PDFs.',
    category: 'business',
    icon: 'print',
    color: '#f97316',
    route: '/tools/business/thermal-receipt',
    tags: ['thermal', 'receipt', 'pos', 'print'],
    isComingSoon: true,
    outputFileTypes: ['.pdf']
  },
  {
    id: 'purchase-order',
    name: 'Purchase Order',
    description: 'Create professional purchase order documents.',
    category: 'business',
    icon: 'shopping_cart',
    color: '#f97316',
    route: '/tools/business/purchase-order',
    tags: ['purchase', 'order', 'po', 'business'],
    isComingSoon: true,
    outputFileTypes: ['.pdf']
  },
  {
    id: 'quote-generator',
    name: 'Quote Generator',
    description: 'Create professional business quotations.',
    category: 'business',
    icon: 'format_quote',
    color: '#f97316',
    route: '/tools/business/quote-generator',
    tags: ['quote', 'estimate', 'business'],
    isComingSoon: true,
    outputFileTypes: ['.pdf']
  },
  {
    id: 'business-letter',
    name: 'Business Letter',
    description: 'Generate professionally formatted business letters.',
    category: 'business',
    icon: 'mail',
    color: '#f97316',
    route: '/tools/business/business-letter',
    tags: ['letter', 'business', 'formal'],
    isComingSoon: true,
    outputFileTypes: ['.pdf']
  },

  // ── AI Tools ────────────────────────────────────────────────────────────────
  {
    id: 'chat-with-pdf',
    name: 'Chat with PDF',
    description: 'Ask questions and get answers from your PDF documents.',
    category: 'ai',
    icon: 'chat',
    color: '#06b6d4',
    route: '/tools/ai/chat-with-pdf',
    tags: ['ai', 'chat', 'question', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'summarize-pdf',
    name: 'Summarize PDF',
    description: 'Get intelligent summaries of long PDF documents.',
    category: 'ai',
    icon: 'summarize',
    color: '#06b6d4',
    route: '/tools/ai/summarize-pdf',
    tags: ['ai', 'summary', 'summarize', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'resume-analysis',
    name: 'Resume Analysis',
    description: 'AI-powered resume review and improvement suggestions.',
    category: 'ai',
    icon: 'analytics',
    color: '#06b6d4',
    route: '/tools/ai/resume-analysis',
    tags: ['ai', 'resume', 'cv', 'analysis'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf', '.docx']
  },
  {
    id: 'contract-analysis',
    name: 'Contract Analysis',
    description: 'Extract key terms and insights from contracts.',
    category: 'ai',
    icon: 'gavel',
    color: '#8B5CF6',
    route: '/tools/ai/contract-analysis',
    tags: ['ai', 'contract', 'legal', 'analysis'],
    isNew: true,
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'flashcard-generator',
    name: 'Flashcard Generator',
    description: 'Create study flashcards from your PDF documents.',
    category: 'ai',
    icon: 'style',
    color: '#06b6d4',
    route: '/tools/ai/flashcard-generator',
    tags: ['ai', 'flashcard', 'study', 'learn'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    description: 'Translate PDF documents to any language with AI.',
    category: 'ai',
    icon: 'translate',
    color: '#06b6d4',
    route: '/tools/ai/translate-pdf',
    tags: ['ai', 'translate', 'language', 'pdf'],
    isComingSoon: true,
    acceptedFileTypes: ['.pdf']
  }
]
